package com.seoulhankuko.app.data.database

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.seoulhankuko.app.data.database.daos.*
import com.seoulhankuko.app.data.database.entities.*

@Database(
    entities = [
        LoggedAccountEntity::class
    ],
    version = 5,
    exportSchema = false
)
@TypeConverters(Converters::class)
abstract class AppDatabase : RoomDatabase() {
    
    abstract fun loggedAccountDao(): LoggedAccountDao
    
    companion object {
        @Volatile
        private var INSTANCE: AppDatabase? = null
        
        /**
         * Migration from version 1 to 2: Add logged_accounts table
         */
        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("""
                    CREATE TABLE IF NOT EXISTS `logged_accounts` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `userId` INTEGER NOT NULL,
                        `email` TEXT NOT NULL,
                        `displayName` TEXT NOT NULL,
                        `photoUrl` TEXT,
                        `accessToken` TEXT,
                        `refreshToken` TEXT,
                        `lastLogin` INTEGER NOT NULL,
                        `isActive` INTEGER NOT NULL DEFAULT 0
                    )
                """.trimIndent())
            }
        }

        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "seoul_hankuko_database"
                )
                .addMigrations(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4, MIGRATION_4_5)
                .build()
                INSTANCE = instance
                instance
            }
        }
        
        /**
         * Migration 2->3: Switch primary keys for lessons, challenges, challenge_options to non-autogenerated IDs.
         * Strategy: create new tables with desired schema, copy data, drop old tables, rename.
         */
        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(database: SupportSQLiteDatabase) {
                // lessons - column order: id, title, unitId, order (to match Room entity order)
                database.execSQL("""
                    CREATE TABLE IF NOT EXISTS `lessons_new` (
                        `id` INTEGER NOT NULL,
                        `title` TEXT NOT NULL,
                        `unitId` INTEGER NOT NULL,
                        `order` INTEGER NOT NULL,
                        PRIMARY KEY(`id`),
                        FOREIGN KEY(`unitId`) REFERENCES `units`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                    )
                """.trimIndent())
                database.execSQL("""
                    INSERT INTO `lessons_new`(`id`,`title`,`unitId`,`order`)
                    SELECT `id`,`title`,`unitId`,`order` FROM `lessons`
                """.trimIndent())
                database.execSQL("DROP TABLE `lessons`")
                database.execSQL("ALTER TABLE `lessons_new` RENAME TO `lessons`")
                // Recreate index on unitId
                database.execSQL("CREATE INDEX IF NOT EXISTS `index_lessons_unitId` ON `lessons`(`unitId`)")

                // challenges - column order: id, lessonId, type, question, order
                database.execSQL("""
                    CREATE TABLE IF NOT EXISTS `challenges_new` (
                        `id` INTEGER NOT NULL,
                        `lessonId` INTEGER NOT NULL,
                        `type` TEXT NOT NULL,
                        `question` TEXT NOT NULL,
                        `order` INTEGER NOT NULL,
                        PRIMARY KEY(`id`),
                        FOREIGN KEY(`lessonId`) REFERENCES `lessons`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                    )
                """.trimIndent())
                database.execSQL("""
                    INSERT INTO `challenges_new`(`id`,`lessonId`,`type`,`question`,`order`)
                    SELECT `id`,`lessonId`,`type`,`question`,`order` FROM `challenges`
                """.trimIndent())
                database.execSQL("DROP TABLE `challenges`")
                database.execSQL("ALTER TABLE `challenges_new` RENAME TO `challenges`")
                // Recreate index on lessonId
                database.execSQL("CREATE INDEX IF NOT EXISTS `index_challenges_lessonId` ON `challenges`(`lessonId`)")

                // challenge_options - column order: id, challengeId, text, correct, imageSrc, audioSrc
                database.execSQL("""
                    CREATE TABLE IF NOT EXISTS `challenge_options_new` (
                        `id` INTEGER NOT NULL,
                        `challengeId` INTEGER NOT NULL,
                        `text` TEXT NOT NULL,
                        `correct` INTEGER NOT NULL,
                        `imageSrc` TEXT,
                        `audioSrc` TEXT,
                        PRIMARY KEY(`id`),
                        FOREIGN KEY(`challengeId`) REFERENCES `challenges`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                    )
                """.trimIndent())
                database.execSQL("""
                    INSERT INTO `challenge_options_new`(`id`,`challengeId`,`text`,`correct`,`imageSrc`,`audioSrc`)
                    SELECT `id`,`challengeId`,`text`,`correct`,`imageSrc`,`audioSrc` FROM `challenge_options`
                """.trimIndent())
                database.execSQL("DROP TABLE `challenge_options`")
                database.execSQL("ALTER TABLE `challenge_options_new` RENAME TO `challenge_options`")
                // Recreate index on challengeId
                database.execSQL("CREATE INDEX IF NOT EXISTS `index_challenge_options_challengeId` ON `challenge_options`(`challengeId`)")
            }
        }

        /**
         * Migration 3->4: Drop local caching tables no longer used
         */
        val MIGRATION_3_4 = object : Migration(3, 4) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("DROP INDEX IF EXISTS `index_challenge_options_challengeId`")
                database.execSQL("DROP INDEX IF EXISTS `index_challenges_lessonId`")
                database.execSQL("DROP INDEX IF EXISTS `index_lessons_unitId`")
                database.execSQL("DROP TABLE IF EXISTS `challenge_options`")
                database.execSQL("DROP TABLE IF EXISTS `challenges`")
                database.execSQL("DROP TABLE IF EXISTS `lessons`")
            }
        }

        /**
         * Migration 4->5: Drop all remaining non-LoggedAccount tables if present
         */
        val MIGRATION_4_5 = object : Migration(4, 5) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("DROP TABLE IF EXISTS `courses`")
                database.execSQL("DROP TABLE IF EXISTS `units`")
                database.execSQL("DROP TABLE IF EXISTS `user_progress`")
                database.execSQL("DROP TABLE IF EXISTS `challenge_progress`")
                database.execSQL("DROP TABLE IF EXISTS `user_subscriptions`")
            }
        }
    }
}
